const args = process.argv.slice(2)
if (args[0] != null) {
  const Tabela = require('./Tabela');
  const Estado = require('./Estado');
  const numero = '0,1,2,3,4,5,6,7,8,9';
  const letras = 'a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z';
  const letrasMaiscula = 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z';
  const outros = '",+,-,*,/,=,<,>,:,;,., ,(,),\\';
  const erros = 'ú,é';
  var tabela = new Tabela();
  var q0 = new Estado(false);
  q0.addTransicao(numero, 22);
  q0.addTransicao(letras, 1);
  q0.addTransicao(erros, 36);
  q0.addTransicao('+',3);
  q0.addTransicao(' ',37);
  q0.addTransicao('-', 4);
  q0.addTransicao('*', 5);
  q0.addTransicao('/', 7);
  q0.addTransicao('"',11);
  q0.addTransicao('=', 15);
  q0.addTransicao('<', 16);
  q0.addTransicao('>', 18);
  q0.addTransicao(':', 21);
  q0.addTransicao(';', 33);
  q0.addTransicao('(', 34);
  q0.addTransicao(')', 35);
  q0.addTransicao('_',38);
  q0.addTransicao(',',39);
  var q1 = new Estado(true, 'tk_IDEN');
  q1.addTransicao(numero, 1);
  q1.addTransicao(letras, 1);
  q1.addTransicao('_',38);
  //q1.addTransicao(outros,2);
  var q2 = new Estado(true, 'tk_IDEN');
  var q3 = new Estado(true, 'tk_mais');
  q3.addTransicao(numero, 22);
  var q4 = new Estado(true, 'tk_menos');
  q4.addTransicao(numero, 24);
  q4.addTransicao('.', 13);
  var q5 = new Estado(true, 'tk_vezes');
  q5.addTransicao('©', 5);
  var q7 = new Estado(true, 'tk_dividido');
  q7.addTransicao('*', 8);
  q7.addTransicao('/', 32);
  var q8 = new Estado(false);
  q8.addTransicao(numero, 8);
  q8.addTransicao(letras, 8);
  q8.addTransicao(letrasMaiscula,8);
  q8.addTransicao(outros.replace('*,', '').replace('/,', ''), 8);
  q8.addTransicao('*,/', 9);
  var q9 = new Estado(true);
  q9.addTransicao(letras, 8);
  q9.addTransicao(numero, 8);
  q9.addTransicao(outros.replace('/,', ''), 8);
  q9.addTransicao('/', 10);
  var q10 = new Estado(true, 'tk_comentario');
  q10.addTransicao('©', 10);
  var q11 = new Estado(false);
  q11.addTransicao(numero, 11);
  q11.addTransicao(letras, 11);
  q11.addTransicao(letrasMaiscula,11);
  q11.addTransicao(outros.replace('"','').replace('/,','').replace('-,',''), 11);
  q11.addTransicao('"', 12);
  q11.addTransicao('/,-', 19);
  var q12 = new Estado(true, 'tk_CADEIA');
  var q13 = new Estado(true, 'tk_DECIMAL');
  q13.addTransicao(numero, 13);
  var q15 = new Estado(true, 'tk_igual');
  q15.addTransicao('=', 15);
  var q16 = new Estado(true, 'tk_maior');
  q16.addTransicao('=', 29);
  q16.addTransicao('>', 27);
  q16.addTransicao('©', 16);
  var q18 = new Estado(true, 'tk_menor');
  q18.addTransicao('=', 28);
  var q19 = new Estado(false);
  q19.addTransicao(letras, 11);
  q19.addTransicao(numero, 11);
  q19.addTransicao(outros.replace(',.', ''), 11);
  var q20 = new Estado(false);
  q20.addTransicao(':', 21);
  var q21 = new Estado(true, 'tk_dois_pts');
  q21.addTransicao('=', 30);
  var q22 = new Estado(true, 'tk_inteiro');
  q22.addTransicao(numero, 22);
  q22.addTransicao('.', 23);
  var q23 = new Estado(true, 'tk_decimal');
  q23.addTransicao(numero, 23);
  var q24 = new Estado(true, 'tk_inteiro');
  q24.addTransicao(numero, 24);
  q24.addTransicao('.',13);
  var q27 = new Estado(true, 'tk_diferente');
  var q28 = new Estado(true, 'tk_maior_igual');
  q28.addTransicao('©', 28);
  var q29 = new Estado(true, 'tk_menor_igual');
  q29.addTransicao('©', 29);
  var q30 = new Estado(true, 'tk_atrib');
  q30.addTransicao('©', 30);
  var q32 = new Estado(true, 'tk_comentario')
  q32.addTransicao(outros, 32);
  q32.addTransicao(letras, 32);
  q32.addTransicao(numero, 32);
  q32.addTransicao(letrasMaiscula,32);
  var q33 = new Estado(true, 'tk_pt_virg');
  var q34 = new Estado(true, 'tk_abre_par');
  var q35 = new Estado(true, 'tk_fecha_par');
  var q36 = new Estado(true, 'erro');
  var q37 = new Estado(true, 'espaco');
  q37.addTransicao(' ',37);
  var q38 = new Estado(true, 'tk_IDEN');
  q38.addTransicao(letras,38);
  var q39 = new Estado(true, 'tk_virg');

  tabela.addEstado(q0, 0);
  tabela.addEstado(q1, 1);
  tabela.addEstado(q2,2);
  tabela.addEstado(q3, 3);
  tabela.addEstado(q4, 4);
  tabela.addEstado(q5, 5);
  tabela.addEstado(q7, 7);
  tabela.addEstado(q8, 8);
  tabela.addEstado(q9, 9);
  tabela.addEstado(q10, 10);
  tabela.addEstado(q11, 11);
  tabela.addEstado(q12, 12);
  tabela.addEstado(q13,13);
  tabela.addEstado(q15, 15);
  tabela.addEstado(q16, 16);
  tabela.addEstado(q18, 18);
  tabela.addEstado(q19, 19);
  tabela.addEstado(q20, 20);
  tabela.addEstado(q21, 21);
  tabela.addEstado(q22, 22);
  tabela.addEstado(q23, 23);
  tabela.addEstado(q24, 24);
  tabela.addEstado(q27, 27);
  tabela.addEstado(q28, 28);
  tabela.addEstado(q29, 29);
  tabela.addEstado(q30, 30);
  tabela.addEstado(q32, 32);
  tabela.addEstado(q33, 33);
  tabela.addEstado(q34, 34);
  tabela.addEstado(q35, 35);
  tabela.addEstado(q36, 36);
  tabela.addEstado(q37, 37);
  tabela.addEstado(q38, 38);
  tabela.addEstado(q39,39);
  var linha = 1;
  require('fs').readFileSync(args[0], 'utf-8').split(/\r?\n/).forEach(function(linhaArquivo) {    
    if(linha == 8) 
      tabela.core(linhaArquivo,linha);
    else 
     tabela.core(linhaArquivo,linha);
    linha++;
  });
}else{
  console.log('arquivo nao informado');
}